In [3]:
import numpy as np
from sklearn.datasets import load_diabetes

In [6]:
X,Y=load_diabetes(return_X_y=True)

In [7]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [8]:
X.shape

(442, 10)

In [9]:
Y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

Sklearn Linear Regression

In [10]:
from sklearn.model_selection import train_test_split

In [13]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=2)

In [14]:
X_train

array([[-0.00188202, -0.04464164, -0.06979687, ..., -0.03949338,
        -0.06291688,  0.04034337],
       [-0.00914709, -0.04464164,  0.01103904, ..., -0.03949338,
         0.01703607, -0.0052198 ],
       [ 0.02354575,  0.05068012, -0.02021751, ..., -0.03949338,
        -0.09643495, -0.01764613],
       ...,
       [ 0.06350368,  0.05068012, -0.00405033, ..., -0.00259226,
         0.08449153, -0.01764613],
       [-0.05273755,  0.05068012, -0.01806189, ...,  0.1081111 ,
         0.03606033, -0.04249877],
       [ 0.00175052,  0.05068012,  0.05954058, ...,  0.1081111 ,
         0.06898589,  0.12732762]])

In [15]:
from sklearn.linear_model import LinearRegression

In [16]:
lr=LinearRegression()

In [20]:
#training hte model
lr.fit(X_train,Y_train)

LinearRegression()

In [21]:
# testing the model
Y_pred=lr.predict(X_test)

In [22]:
# calculating r2 score
from sklearn.metrics import r2_score

In [23]:
r2_score(Y_test,Y_pred)

0.4399338661568969

In [24]:
# calcuating coefficients
lr.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [25]:
# calculating intercept
lr.intercept_

151.88331005254167

Making own Linear Regression Class

In [36]:
class MyLR:
    def _init_(self):
        self.coef_=None
        self.intecept_=None
    def fit(self,X_train,Y_train):
        # adding first column with all value as 1
        X_train=np.insert(X_train,0,1,axis=1)
        # calculating coefficients
        betas=np.linalg.inv(np.dot(X_train.T,X_train)).dot(X_train.T).dot(Y_train)      
        self.intercept_=betas[0]
        self.coef_=betas [1:]
    def predict(self,X_test):
        return np.dot(X_test,self.coef_)+self.intercept_
        
        

In [37]:
mlr=MyLR()

In [38]:
# training the model
mlr.fit(X_train,Y_train)

In [39]:
# testig the model
y_pred=mlr.predict(X_test)

In [40]:
# calculating r2_score
r2_score(Y_test,y_pred)

0.43993386615689656

In [41]:
# calculating coefficients
mlr.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [42]:
# calculating intecept
mlr.intercept_

151.88331005254176

Comparing Both Models 

On basis of R2 Score

In [44]:
# for sklearn class
r1=r2_score(Y_test,Y_pred)
# for own class
r2=r2_score(Y_test,y_pred)

In [45]:
print(r1,r2)

0.4399338661568969 0.43993386615689656


Therefore both model has almost same r2 score 

On basis of Coefficient

In [46]:
# from sklearn 
c1=lr.coef_
# from own class
c2=mlr.coef_

In [47]:
print(c1,c2)

[  -9.15865318 -205.45432163  516.69374454  340.61999905 -895.5520019
  561.22067904  153.89310954  126.73139688  861.12700152   52.42112238] [  -9.15865318 -205.45432163  516.69374454  340.61999905 -895.5520019
  561.22067904  153.89310954  126.73139688  861.12700152   52.42112238]


Therefore both model has almost same values of coefficient

On basis of intercept

In [48]:
# from sklearn 
i1=lr.intercept_
# from own class
i2=mlr.intercept_

In [49]:
print(i1,i2)

151.88331005254167 151.88331005254176


Therefore both model has almost same values of intercept